export const questions = [
  ['¿En qué punto está vuestro proyecto de IA?', 'What stage is your AI project at?', ['Explorando ideas', 'Haciendo un piloto', 'En producción'], ['Exploring ideas', 'Running a pilot', 'In production'], '', ''],
  ['¿Tenéis definido qué resultado debe conseguir y cómo medirlo?', 'Have you defined the outcome and how to measure it?', ['No todavía', 'Tenemos una idea', 'Tenemos indicadores y objetivos claros'], ['Not yet', 'We have an idea', 'We have clear metrics and targets'], 'Definid una tarea concreta, un indicador de éxito y un umbral de aceptación antes de ampliar el alcance.', 'Define one task, a success metric and an acceptance threshold before expanding scope.'],
  ['¿Tenéis casos de prueba para evaluar la calidad de las respuestas?', 'Do you have test cases to evaluate answer quality?', ['No', 'Probamos algunos casos manualmente', 'Tenemos un conjunto de pruebas sistemático'], ['No', 'We test a few cases manually', 'We have a systematic test set'], 'Reunid 20–30 casos representativos, incluidos errores frecuentes, y acordad qué respuesta sería aceptable.', 'Collect 20–30 representative cases, including common failures, and agree on acceptable answers.'],
  ['¿Comprobáis la calidad al cambiar el modelo o las instrucciones?', 'Do you check quality when changing models or prompts?', ['No', 'Lo revisamos manualmente', 'Ejecutamos evaluaciones antes de cada cambio'], ['No', 'We review manually', 'We run evaluations before each change'], 'Comparad cada cambio con la versión anterior sobre los mismos casos y bloquead regresiones antes de publicar.', 'Compare changes against the previous version on the same cases and block regressions before release.'],
  ['¿Podéis ver qué ocurre dentro de cada interacción con la IA?', 'Can you see what happens inside each AI interaction?', ['No', 'Revisamos logs básicos', 'Tenemos trazas con Langfuse, LangSmith, Phoenix u otra herramienta'], ['No', 'We review basic logs', 'We have traces with Langfuse, LangSmith, Phoenix or another tool'], 'Registrad modelo, versión de instrucciones, pasos, errores y tiempos por interacción, minimizando los datos personales.', 'Record model, prompt version, steps, errors and timings per interaction while minimising personal data.'],
  ['¿Medís cuánto cuesta cada tarea y cuánto tarda en responder?', 'Do you measure cost and response time per task?', ['No', 'Miramos el consumo general', 'Medimos costes y tiempos por tarea'], ['No', 'We track overall usage', 'We measure cost and latency per task'], 'Medid coste por tarea completada y latencia habitual y en los casos más lentos; fijad presupuestos y alertas.', 'Measure cost per completed task and typical and tail latency; set budgets and alerts.'],
  ['¿Controláis qué datos y herramientas puede utilizar la IA?', 'Do you control which data and tools the AI can access?', ['No lo tenemos definido', 'Hay algunas restricciones', 'Hay permisos y controles claros'], ['We have not defined this', 'There are some restrictions', 'We have clear permissions and controls'], 'Definid permisos mínimos por usuario y herramienta, y exigid confirmación para acciones sensibles.', 'Define minimum permissions per user and tool, and require confirmation for sensitive actions.'],
  ['¿Probáis errores, instrucciones maliciosas y exposición de datos sensibles?', 'Do you test failures, malicious instructions and sensitive data exposure?', ['No', 'Hacemos pruebas puntuales', 'Tenemos pruebas y medidas de protección'], ['No', 'We run occasional tests', 'We have tests and safeguards'], 'Añadid casos de inyección de instrucciones, acceso indebido y filtración de datos a las pruebas del sistema.', 'Add prompt injection, unauthorised access and data leakage scenarios to your system tests.'],
  ['¿Qué ocurre cuando la IA falla o no sabe resolver una petición?', 'What happens when the AI fails or cannot resolve a request?', ['No hay un proceso definido', 'Revisamos el problema después', 'Hay alternativa o intervención humana prevista'], ['There is no defined process', 'We review the problem afterwards', 'There is a fallback or human handover'], 'Definid cuándo detenerse, reintentar o derivar a una persona; mostrad al usuario un siguiente paso claro.', 'Define when to stop, retry or hand over to a person; give users a clear next step.'],
  ['¿Usáis errores y valoraciones de usuarios para mejorar el sistema?', 'Do you use errors and user feedback to improve the system?', ['No', 'Recogemos comentarios informalmente', 'Tenemos un proceso continuo de mejora'], ['No', 'We collect informal feedback', 'We have a continuous improvement process'], 'Revisad fallos y comentarios periódicamente, asignad responsables y convertid cada fallo relevante en un caso de prueba.', 'Review failures and feedback regularly, assign owners and turn significant failures into test cases.'],
] as const;
export function evaluate(answers: number[]) {
  if (answers.length !== 10 || answers.some(a => !Number.isInteger(a) || a < 0 || a > 2)) throw new Error('Incomplete diagnosis');
  const points = answers.slice(1).reduce((a, b) => a + b, 0);
  const score = Math.round((1 + points / 2) * 10) / 10;
  // Safety and evaluation come first when multiple gaps have the same score.
  const order = [6, 7, 2, 3, 8, 1, 4, 5, 9];
  const priorities = order.filter(i => answers[i] < 2).sort((a, b) => answers[a] - answers[b]).slice(0, 3);
  return { score, points, priorities, level: score < 4 ? 0 : score < 7 ? 1 : score < 9 ? 2 : 3 };
}

// A concrete deliverable for each priority, included only in the downloaded report.
export const priorityEvidence = [
  ['', ''],
  ['Una ficha con tarea, indicador, umbral de aceptación y responsable acordados por producto e ingeniería.', 'A brief with the task, metric, acceptance threshold and owner agreed by product and engineering.'],
  ['Un conjunto versionado de casos con respuesta esperada, criterio de aceptación y resultado de la evaluación inicial.', 'A versioned test set with expected answers, acceptance criteria and baseline evaluation results.'],
  ['Una comparación reproducible entre versiones y un criterio explícito para aceptar o bloquear el cambio.', 'A reproducible comparison between versions and an explicit rule for accepting or blocking a change.'],
  ['Una traza completa de una petición de prueba, con pasos, versiones, errores y tiempos, sin exponer datos sensibles.', 'A complete trace of a test request showing steps, versions, errors and timings without exposing sensitive data.'],
  ['Un panel por tarea con coste, latencia y umbrales de alerta; comprobad que una alerta de prueba llega al responsable.', 'A per-task dashboard showing cost, latency and alert thresholds; verify a test alert reaches its owner.'],
  ['Una matriz de permisos y pruebas que demuestren que un usuario no accede a datos ni ejecuta acciones fuera de su ámbito.', 'A permissions matrix and tests showing users cannot access data or perform actions outside their scope.'],
  ['Un registro de escenarios adversos, resultados y medidas correctoras; repetid los casos después de aplicar las medidas.', 'A record of adversarial scenarios, results and fixes; rerun the cases after applying the fixes.'],
  ['Un procedimiento de recuperación probado con un fallo simulado, incluyendo responsable y siguiente paso para el usuario.', 'A recovery procedure tested with a simulated failure, including an owner and a clear next step for the user.'],
  ['Un registro de fallos priorizados, responsables y casos nuevos incorporados a la siguiente evaluación.', 'A prioritised failure log with owners and new cases included in the next evaluation.'],
] as const;
